# Generated by Django 5.1.7 on 2025-12-14 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.products'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
    ]
