# Generated by Django 5.1.7 on 2025-12-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_bookingitem_product_alter_bookingitem_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebooking',
            name='total',
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='BookingItem',
        ),
    ]
