# Generated by Django 5.1.7 on 2025-12-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_tablebooking_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['categoryName'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='CategoryID',
            new_name='categoryId',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='CategoryName',
            new_name='categoryName',
        ),
    ]
