# Generated by Django 5.1.7 on 2025-12-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cart_delete_carts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('cartId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('productId', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField(default=1)),
                ('img', models.ImageField(blank=True, null=True, upload_to='cart_items/')),
                ('items', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='payment_method',
            field=models.CharField(choices=[('none', 'Not Selected'), ('shop', 'Pay at Shop'), ('aba', 'ABA Pay')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
